[package]
name = "wasm-piano"
version = "0.2.0"
edition = "2024"

[dependencies]
leptos = { version = "0.8", features = ["csr"] }

[dependencies.web-sys]
version = "0.3"
features = [
    "AudioContext",
    "AudioDestinationNode",
    "AudioParam",
    "GainNode",
    "OscillatorNode",
    "OscillatorType",
    "PointerEvent",
    "Window",
]
